# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bahana' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Bahana
  pod 'Alamofire'
  pod 'Eureka'
  pod 'SwiftyJSON'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
end
